# Parameters for high density data
# output folders
results_dir: "results/"
example: ["example2WGS"]

# input data folder
data_dir: "data/"

variants:
  min_markers: 5
  fuse_adjacent: True
  fuse_adjacent_nr: 3
  n_fraction_max: 0.3
  min_var_length: 100000

homozygosity_params:
  density: 50
  kb: 300
  snp: 37
  window_missing: 1
  window_snp: 50
  window_het : 4