# Parameters for high density data
# output folders
input: "example2WGS"
output: "results/example2WGS"
program_folder: "/data/groups/itz/tools/halfsib_analysis/"
species: "dog"

# input data folder
data_dir: "data/"

filter:
  me: 0.05 0.1
  geno: 0.1
  mind: 0.1
  maf: 0.01


variants:
  min_markers: 5
  fuse_adjacent: True
  fuse_adjacent_nr: 3
  n_fraction_max: 0.3
  min_var_length: 100000

homozygosity_params:
  density: 50
  kb: 300
  snp: 37
  window_missing: 1
  window_snp: 50
  window_het : 4